AuthService
inasahmic/iOSApp pull request #2
Opened 2021-03-26 12:22 UTC by inasahmic

2021-03-27 20:05 UTC, ModernMantra requested changes

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Login/AuthService.swift
> +        let urlString: String = "https://api.themoviedb.org/3/authentication/token/new?api_key=d406343e263966e23c87fce5a21b0bc9"
Please, make one struct called constants and declare within it static constant called api key. after that, make string interpolation by calling 

'https://api.themoviedb.org/3/authentication/token/new?api_key=\(Constants.API_KEY)"

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Login/AuthService.swift
> +                self.expiresAt = expiresAt as? String
make one space empty after delcaring all variables/constants

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Login/AuthService.swift
> +
empty space, remove it

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Login/LoginViewController.swift
> +        let service = AuthService()
move thisdeclaration to top of the function, so it will look like having one after another delcarations.

        let viewcontoroller = storyboard.instantiateViewController(identifier: "RegistrationViewController")
        let service = AuthService()

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Login/LoginViewController.swift
> +
only one empty space should be between function delcarations

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Login/LoginViewController.swift
> +            NSLog("The \"OK\" alert occured.")
indentation wrong

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Login/LoginViewController.swift
> +            NSLog("The \"OK\" alert occured.")
indentation

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Registration/RegistrationSecondViewController.swift
> +
empty space

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Registration/RegistrationSecondViewController.swift
> +        let viewcontoroller = storyboard.instantiateViewController(identifier: "LoginViewController")
String has nice function that might help in this situation. 
Namely, you can use String(describing: LoginViewController.self) and have the same result.

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Registration/RegistrationSecondViewController.swift
> +        let viewcontoroller = storyboard.instantiateViewController(identifier: "RegistrationViewController")
same like comment above, use String(describing:)

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Registration/RegistrationSecondViewController.swift
> +
empty space

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Registration/RegistrationSecondViewController.swift
> +            NSLog("The \"OK\" alert occured.")
indentation

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Registration/RegistrationSecondViewController.swift
> +            NSLog("The \"OK\" alert occured.")
indentation

2021-03-27 20:05 UTC, ModernMantra commented on iOSApp/Screens/Registration/RegistrationViewController.swift
> +            NSLog("The \"OK\" alert occured.")
indentation

2021-03-27 20:07 UTC, ModernMantra commented
please use some better messages in commits, all of them has name update.

2021-03-27 20:08 UTC, ModernMantra commented
> No description provided.

Please add some here description about the job done.

2021-03-28 16:40 UTC, inasahmic commented
I fixed all of the issues addressed in this pull request.

2021-03-28 18:26 UTC, merged